using System;
using System.Collections.Generic;

namespace AgentRiskScore.Models
{
    public partial class Account
    {
        public int CodeComp { get; set; }
        public int CodeOrg { get; set; }
        public string NoMaster { get; set; }
        public string NoCif { get; set; }
        public string NoAcc { get; set; }
        public string InfoName { get; set; }
        public int? AccStatus { get; set; }
        public string AccIplace { get; set; }
        public int? AccCdate { get; set; }
        public int? AccJoint { get; set; }
        public int? AccUdate { get; set; }
        public string AccOther { get; set; }
        public double? Bal1Val { get; set; }
        public double? Bal2Val { get; set; }
        public double? Bal1Avg { get; set; }
        public double? Bal2Avg { get; set; }
        public double? Bal1Out { get; set; }
        public double? Bal2Out { get; set; }
        public int? AccType { get; set; }
        public int? AccProd { get; set; }
        public int? AccStype { get; set; }
        public int? AccSprod { get; set; }
        public string TypeFaci { get; set; }
        public int? TypeCons { get; set; }
        public int? PayDur { get; set; }
        public int? PayFreq { get; set; }
        public double? PayIrate { get; set; }
        public double? PayLimit { get; set; }
        public int? TypeCover { get; set; }
        public int? TypePrem { get; set; }
        public int? DateInv { get; set; }
        public int? DateRedem { get; set; }
        public int? DateRenew { get; set; }
        public double? PayDburse { get; set; }
        public int? DburseDate { get; set; }
        public double? PayAmount { get; set; }
        public int? PayDate { get; set; }
        public double? PayAdvance { get; set; }
        public int? PayDdate { get; set; }
        public double? PaySettle { get; set; }
        public int? PaySdate { get; set; }
        public string AgCat { get; set; }
        public string AgNo { get; set; }
        public string AgName { get; set; }
        public string CtcNo { get; set; }
        public string CtcName { get; set; }
        public int? CtcRdate { get; set; }
        public double? PremAmount { get; set; }
        public string PremRlen { get; set; }
        public int? PremPdate { get; set; }
        public int? PremRdate { get; set; }
        public int? PremDdate { get; set; }
        public double? PremAdv { get; set; }
        public int? PremNdate { get; set; }
        public int? FlagFpos { get; set; }
        public int? FposDate { get; set; }
        public string DataValue01 { get; set; }
        public string DataValue02 { get; set; }
        public string DataValue03 { get; set; }
        public string DataValue04 { get; set; }
        public string DataValue05 { get; set; }
        public string DataValue06 { get; set; }
        public string DataValue07 { get; set; }
        public string DataValue08 { get; set; }
        public string DataValue09 { get; set; }
        public string DataValue10 { get; set; }
        public string DataValue11 { get; set; }
        public string DataValue12 { get; set; }
        public string DataValue13 { get; set; }
        public string DataValue14 { get; set; }
        public string DataValue15 { get; set; }
        public string DataValue16 { get; set; }
        public string DataValue17 { get; set; }
        public string DataValue18 { get; set; }
        public string DataValue19 { get; set; }
        public string DataValue20 { get; set; }
        public string DataValue21 { get; set; }
        public string DataValue22 { get; set; }
        public string DataValue23 { get; set; }
        public string DataValue24 { get; set; }
        public string DataValue25 { get; set; }
        public string DataValue26 { get; set; }
        public string DataValue27 { get; set; }
        public string DataValue28 { get; set; }
        public string DataValue29 { get; set; }
        public string DataValue30 { get; set; }
        public string DataValue31 { get; set; }
        public string DataValue32 { get; set; }
        public string DataValue33 { get; set; }
        public string DataValue34 { get; set; }
        public string DataValue35 { get; set; }
        public string DataValue36 { get; set; }
        public string DataValue37 { get; set; }
        public string DataValue38 { get; set; }
        public string DataValue39 { get; set; }
        public string DataValue40 { get; set; }
        public string DataValue41 { get; set; }
        public string DataValue42 { get; set; }
        public string DataValue43 { get; set; }
        public string DataValue44 { get; set; }
        public string DataValue45 { get; set; }
        public string DataValue46 { get; set; }
        public string DataValue47 { get; set; }
        public string DataValue48 { get; set; }
        public string DataValue49 { get; set; }
        public string DataValue50 { get; set; }
        public string DataValue51 { get; set; }
        public string DataValue52 { get; set; }
        public string DataValue53 { get; set; }
        public string DataValue54 { get; set; }
        public string DataValue55 { get; set; }
        public int? BatchDate { get; set; }
        public string BatchNo { get; set; }
        public DateTime? AuditCreatedDate { get; set; }
        public string AuditCreatedUser { get; set; }
        public DateTime? AuditUpdatedDate { get; set; }
        public string AuditUpdatedUser { get; set; }
    }
}
