using System;
using System.Collections.Generic;

namespace AgentRiskScore.Models
{
    public partial class Apiswift
    {
        public long Id { get; set; }
        public string OfficerId { get; set; }
        public string Location { get; set; }
        public string Source { get; set; }
        public string ServiceType { get; set; }
        public string RedFlagType { get; set; }
        public string FileId { get; set; }
        public string MsgId { get; set; }
        public DateTime CreDtTm { get; set; }
        public int NbOfTxs { get; set; }
        public decimal TtlAmt { get; set; }
        public string TtlAmtCcy { get; set; }
        public int SttlmInfDate { get; set; }
        public string SttlmInfMethod { get; set; }
        public string SttlmInfClientNo { get; set; }
        public string SttlmInfAccountNo { get; set; }
        public string SttlmInfIdno { get; set; }
        public string SttlmInfIban { get; set; }
        public string InstructingAgentBicfi { get; set; }
        public string InstructedAgentBicfi { get; set; }
        public string PayInfoDirection { get; set; }
        public string PayInfoInstrId { get; set; }
        public string PayInfoEndToEndId { get; set; }
        public string PayInfoTxnId { get; set; }
        public string PayInfoInstrPriority { get; set; }
        public string PayInfoProprietary { get; set; }
        public string PayInfoSeqType { get; set; }
        public string PayInfoFreqType { get; set; }
        public string PayInfoCcy { get; set; }
        public decimal PayInfoAmt { get; set; }
        public int PayInfoDate { get; set; }
        public string PayInfoTownName { get; set; }
        public string PayInfoCountrySubDivision { get; set; }
        public string PayInfoCountry { get; set; }
        public DateTime? PayInfoExpDtTm { get; set; }
        public string PayInfoAutoExtPeriod { get; set; }
        public int? PayInfoFinalExpDt { get; set; }
        public string SenderName { get; set; }
        public string SenderProxyName { get; set; }
        public string SenderStreetName { get; set; }
        public string SenderBuildingNo { get; set; }
        public string SenderBuildingName { get; set; }
        public string SenderBuildingFloor { get; set; }
        public string SenderPostBox { get; set; }
        public string SenderPostCode { get; set; }
        public string SenderTownName { get; set; }
        public string SenderTownLocationName { get; set; }
        public string SenderDistrictName { get; set; }
        public string SenderCountrySubDiv { get; set; }
        public string SenderCountry { get; set; }
        public string SenderAccountNo { get; set; }
        public string SenderIdno { get; set; }
        public string SenderIban { get; set; }
        public string SenderBicfi { get; set; }
        public string BeneName { get; set; }
        public string BeneProxyName { get; set; }
        public string BeneStreetName { get; set; }
        public string BeneBuildingNo { get; set; }
        public string BeneBuildingName { get; set; }
        public string BeneBuildingFloor { get; set; }
        public string BenePostBox { get; set; }
        public string BenePostCode { get; set; }
        public string BeneTownName { get; set; }
        public string BeneTownLocationName { get; set; }
        public string BeneDistrictName { get; set; }
        public string BeneCountrySubDiv { get; set; }
        public string BeneCountry { get; set; }
        public string BeneAddressLine { get; set; }
        public string BeneAccountNo { get; set; }
        public string BeneIdno { get; set; }
        public string BeneIban { get; set; }
        public string BeneBicfi { get; set; }
        public string PurposeCodeOrProp { get; set; }
        public string PresntnPlace { get; set; }
        public string PresntnCountry { get; set; }
        public string PresntnConfirmation { get; set; }
        public string PresntnDocCodeorProp { get; set; }
        public string PresntnWording { get; set; }
        public string PresntnElctrncDtlsCodeorProp { get; set; }
        public string DocType { get; set; }
        public string DlvryPartyType { get; set; }
        public string DlvryName { get; set; }
        public string DlvryAddType { get; set; }
        public string DlvryAddStreetName { get; set; }
        public string DlvryAddBuildingNo { get; set; }
        public string DlvryAddPostCode { get; set; }
        public string DlvryAddTownName { get; set; }
        public string DlvryAddCountrySubDiv { get; set; }
        public string DlvryAddCountry { get; set; }
        public string DlvryAddressLine { get; set; }
        public string TransferInd { get; set; }
        public string BankToBeneInfo { get; set; }
        public string BankToBankInfo { get; set; }
        public string RmtInfoCode { get; set; }
        public string RmtInfoProprietary { get; set; }
        public string RmtInfoNo { get; set; }
        public int? RmtInfoRelatedDt { get; set; }
        public string RmtInfoUnstructured { get; set; }
        public string TxnScreeningNo { get; set; }
        public string MatchStatus { get; set; }
        public string WhitelistStatus { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
    }
}
