using System;
using System.Collections.Generic;

namespace AgentRiskScore.Models
{
    public partial class RelUbo
    {
        public long SeqNo { get; set; }
        public string InfoName { get; set; }
        public string NoMaster { get; set; }
        public string NoCif { get; set; }
        public int CodeComp { get; set; }
        public int NoUbo { get; set; }
        public int CodeOrg { get; set; }
        public string NoRef { get; set; }
        public string RelayStat { get; set; }
        public string InfoType { get; set; }
        public int? IdType { get; set; }
        public string IdNo { get; set; }
        public int? Id2Type { get; set; }
        public string Id2No { get; set; }
        public int? InfoNat { get; set; }
        public int? InfoRes { get; set; }
        public int? InfoAge { get; set; }
        public int? InfoDob { get; set; }
        public string Occ { get; set; }
        public string OccSect { get; set; }
        public string OccPos { get; set; }
        public string Buss { get; set; }
        public string BussSect { get; set; }
        public string DataValue01 { get; set; }
        public string DataValue02 { get; set; }
        public string DataValue03 { get; set; }
        public string DataValue04 { get; set; }
        public string DataValue05 { get; set; }
        public string DataValue06 { get; set; }
        public string DataValue07 { get; set; }
        public string DataValue08 { get; set; }
        public string DataValue09 { get; set; }
        public string DataValue10 { get; set; }
        public string DataValue11 { get; set; }
        public string DataValue12 { get; set; }
        public string DataValue13 { get; set; }
        public string DataValue14 { get; set; }
        public string DataValue15 { get; set; }
        public string DataValue16 { get; set; }
        public string DataValue17 { get; set; }
        public string DataValue18 { get; set; }
        public string DataValue19 { get; set; }
        public string DataValue20 { get; set; }
        public string DataValue21 { get; set; }
        public string DataValue22 { get; set; }
        public string DataValue23 { get; set; }
        public string DataValue24 { get; set; }
        public string DataValue25 { get; set; }
        public string DataValue26 { get; set; }
        public string DataValue27 { get; set; }
        public string DataValue28 { get; set; }
        public string DataValue29 { get; set; }
        public string DataValue30 { get; set; }
        public string DataValue31 { get; set; }
        public string DataValue32 { get; set; }
        public string DataValue33 { get; set; }
        public string DataValue34 { get; set; }
        public string DataValue35 { get; set; }
        public string DataValue36 { get; set; }
        public string DataValue37 { get; set; }
        public string DataValue38 { get; set; }
        public string DataValue39 { get; set; }
        public string DataValue40 { get; set; }
        public string DataValue41 { get; set; }
        public string DataValue42 { get; set; }
        public string DataValue43 { get; set; }
        public string DataValue44 { get; set; }
        public string DataValue45 { get; set; }
        public string DataValue46 { get; set; }
        public string DataValue47 { get; set; }
        public string DataValue48 { get; set; }
        public string DataValue49 { get; set; }
        public string DataValue50 { get; set; }
        public string DataValue51 { get; set; }
        public string DataValue52 { get; set; }
        public string DataValue53 { get; set; }
        public string DataValue54 { get; set; }
        public string DataValue55 { get; set; }
        public int? BatchDate { get; set; }
        public string BatchNo { get; set; }
        public DateTime? AuditCreatedDate { get; set; }
        public string AuditCreatedUser { get; set; }
        public int? CtcHome { get; set; }
        public string Email { get; set; }
        public int? CtcMobile { get; set; }
        public int? CtcOffice { get; set; }
        public string InfoAdd1 { get; set; }
        public string InfoAdd2 { get; set; }
        public string InfoAdd3 { get; set; }
        public string InfoAdd4 { get; set; }
        public string InfoCity { get; set; }
        public string InfoPcode { get; set; }
        public string InfoState { get; set; }
        public string InfoCountry { get; set; }
        public int? InfoGen { get; set; }
    }
}
