using System;
using System.Collections.Generic;

namespace AgentRiskScore.Models
{
    public partial class TxnReportMisc
    {
        public short CompCode { get; set; }
        public long AlertId { get; set; }
        public short RptType { get; set; }
        public int SeqNo { get; set; }
        public string AcctBr { get; set; }
        public string AlertBr { get; set; }
        public int TranDate { get; set; }
        public short CreditDebit { get; set; }
        public double TranAmount { get; set; }
        public double ForeignAmount { get; set; }
        public double FxRate { get; set; }
        public string LocalCurrency { get; set; }
        public string TranCode { get; set; }
        public long HitTranAutoId { get; set; }
        public long? HitTranhistAutoId { get; set; }
        public short ApprovalStatus { get; set; }
        public int CompletedInd { get; set; }
        public string Tfield01 { get; set; }
        public string Tfield02 { get; set; }
        public string Tfield03 { get; set; }
        public string Tfield04 { get; set; }
        public string Tfield05 { get; set; }
        public string Tfield06 { get; set; }
        public string Tfield07 { get; set; }
        public string Tfield08 { get; set; }
        public string Tfield09 { get; set; }
        public string Tfield10 { get; set; }
        public string Tfield11 { get; set; }
        public string Tfield12 { get; set; }
        public string Tfield13 { get; set; }
        public string Tfield14 { get; set; }
        public string Tfield15 { get; set; }
        public string Tfield16 { get; set; }
        public string Tfield17 { get; set; }
        public string Tfield18 { get; set; }
        public string Tfield19 { get; set; }
        public string Tfield20 { get; set; }
        public string Tfield21 { get; set; }
        public string Tfield22 { get; set; }
        public string Tfield23 { get; set; }
        public string Tfield24 { get; set; }
        public string Tfield25 { get; set; }
        public string Tfield26 { get; set; }
        public string Tfield27 { get; set; }
        public string Tfield28 { get; set; }
        public string Tfield29 { get; set; }
        public string Tfield30 { get; set; }
        public string Tfield31 { get; set; }
        public string Tfield32 { get; set; }
        public string Tfield33 { get; set; }
        public string Tfield34 { get; set; }
        public string Tfield35 { get; set; }
        public string Tfield36 { get; set; }
        public string Tfield37 { get; set; }
        public string Tfield38 { get; set; }
        public string Tfield39 { get; set; }
        public string Tfield40 { get; set; }
        public string Tfield41 { get; set; }
        public string Tfield42 { get; set; }
        public string Tfield43 { get; set; }
        public string Tfield44 { get; set; }
        public string Tfield45 { get; set; }
        public string Tfield46 { get; set; }
        public string Tfield47 { get; set; }
        public string Tfield48 { get; set; }
        public string Tfield49 { get; set; }
        public string Tfield50 { get; set; }
        public string Tfield51 { get; set; }
        public string Tfield52 { get; set; }
        public string Tfield53 { get; set; }
        public string Tfield54 { get; set; }
        public string Tfield55 { get; set; }
        public string Tfield56 { get; set; }
        public string Tfield57 { get; set; }
        public string Tfield58 { get; set; }
        public string Tfield59 { get; set; }
        public string Tfield60 { get; set; }
        public string Tfield61 { get; set; }
        public string Tfield62 { get; set; }
        public string Tfield63 { get; set; }
        public string Tfield64 { get; set; }
        public string Tfield65 { get; set; }
        public string Tfield66 { get; set; }
        public string Tfield67 { get; set; }
        public string Tfield68 { get; set; }
        public string Tfield69 { get; set; }
        public string Tfield70 { get; set; }
        public string Tfield71 { get; set; }
        public string Tfield72 { get; set; }
        public string Tfield73 { get; set; }
        public string Tfield74 { get; set; }
        public string Tfield75 { get; set; }
        public string Tfield76 { get; set; }
        public string Tfield77 { get; set; }
        public string Tfield78 { get; set; }
        public string Tfield79 { get; set; }
        public string Tfield80 { get; set; }
        public string Tfield81 { get; set; }
        public string Tfield82 { get; set; }
        public string Tfield83 { get; set; }
        public string Tfield84 { get; set; }
        public string Tfield85 { get; set; }
        public string Tfield86 { get; set; }
        public string Tfield87 { get; set; }
        public string Tfield88 { get; set; }
        public string Tfield89 { get; set; }
        public string Tfield90 { get; set; }
        public string Tfield91 { get; set; }
        public string Tfield92 { get; set; }
        public string Tfield93 { get; set; }
        public string Tfield94 { get; set; }
        public string Tfield95 { get; set; }
        public string Tfield96 { get; set; }
        public string Tfield97 { get; set; }
        public string Tfield98 { get; set; }
        public string Tfield99 { get; set; }
        public string Tfield100 { get; set; }
        public string Tfield101 { get; set; }
        public string Tfield102 { get; set; }
        public string Tfield103 { get; set; }
        public string Tfield104 { get; set; }
        public string Tfield105 { get; set; }
        public string Tfield106 { get; set; }
        public string Tfield107 { get; set; }
        public string Tfield108 { get; set; }
        public string Tfield109 { get; set; }
        public string Tfield110 { get; set; }
        public string Tfield111 { get; set; }
        public string Tfield112 { get; set; }
        public string Tfield113 { get; set; }
        public string Tfield114 { get; set; }
        public string Tfield115 { get; set; }
        public string Tfield116 { get; set; }
        public string Tfield117 { get; set; }
        public string Tfield118 { get; set; }
        public string Tfield119 { get; set; }
        public string Tfield120 { get; set; }
        public string Mfield01 { get; set; }
        public string Mfield02 { get; set; }
        public int DateExported { get; set; }
        public string ExportedBy { get; set; }
        public int CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedUserId { get; set; }
        public string FinsRefNo { get; set; }
        public int FinsSubmitDate { get; set; }
        public double FinsSubmitTime { get; set; }
        public int StrCloseDt { get; set; }
        public DateTime? StrCloseDttm { get; set; }
        public string ClosedBy { get; set; }
        public string ParticipantType { get; set; }
        public string ReportingEntityId { get; set; }
        public string ReportIndentifier { get; set; }
        public int ReportPrDate { get; set; }
        public int ReportTxDate { get; set; }
        public string ReportAmendedPrev { get; set; }
    }
}
