
IF OBJECT_ID('WORD_SCAN_SOURCE') IS NOT NULL
	DROP TABLE WORD_SCAN_SOURCE
GO
CREATE TABLE [dbo].[WORD_SCAN_SOURCE](
	[id] [bigint] NOT NULL,
	[word] [varchar](500) NOT NULL,
	[word_tmp] [varchar](500) NULL,
	[subword] [varchar](500) NULL,
 CONSTRAINT [PK_WORD_SCAN_SOURCE] PRIMARY KEY CLUSTERED 
(
	[id] ASC,
	[word] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('WORD_SCAN_TEMP') IS NOT NULL
	DROP TABLE WORD_SCAN_TEMP
GO
CREATE TABLE [dbo].[WORD_SCAN_TEMP](
	[id] [bigint] NOT NULL,
	[seq] [int] NOT NULL,
	[fullname] [varchar](500) NULL,
	[partialname] [varchar](500) NULL,
 CONSTRAINT [PK_WORD_PARTIAL_NAME] PRIMARY KEY CLUSTERED 
(
	[id] ASC,
	[seq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('WORD_SCAN_SPLIT1') IS NOT NULL
	DROP TABLE WORD_SCAN_SPLIT1
GO
CREATE TABLE [dbo].[WORD_SCAN_SPLIT1](
	[sysid] [int] IDENTITY(1,1) NOT NULL,
	[wordid] [int] NULL,
	[partialNameSeq] [int] NULL,
	[redundantNameSeq] [int] NULL,
	[fullname] [varchar](500) NULL,
	[partialname] [varchar](500) NULL,
 CONSTRAINT [PK_WORD_SCAN_SPLIT2] PRIMARY KEY CLUSTERED 
(
	[sysid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('WORD_SCAN_SPLIT2') IS NOT NULL
	DROP TABLE WORD_SCAN_SPLIT2
GO
CREATE TABLE [dbo].[WORD_SCAN_SPLIT2](
	[sysid] [int] IDENTITY(1,1) NOT NULL,
	[wordid] [int] NULL,
	[partialNameSeq] [int] NULL,
	[redundantNameSeq] [int] NULL,
	[fullname] [varchar](500) NULL,
	[partialname] [varchar](500) NULL,
 CONSTRAINT [PK_WORD_SCAN_SPLIT2] PRIMARY KEY CLUSTERED 
(
	[sysid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('WORD_SCAN_CONCAT') IS NOT NULL
	DROP TABLE WORD_SCAN_CONCAT
GO
CREATE TABLE [dbo].[WORD_SCAN_CONCAT](
	[id1] [int] NOT NULL,
	[id2] [int] NOT NULL,
	[fullname1] [varchar](500) NULL,
	[fullname2] [varchar](500) NULL,
	[matchedWord] [varchar](500) NULL,
	[minLength] [numeric](8, 4) NULL,
	[maxLength] [numeric](8, 4) NULL,
	[unmatchedWord1] [varchar](500) NULL,
	[unmatchedWord2] [varchar](500) NULL,
	[matchedCount] [int] NOT NULL,
	[unmatchedCount1] [int] NOT NULL,
	[unmatchedCount2] [int] NOT NULL,
	[score] [numeric](8, 4) NULL,
 CONSTRAINT [PK_WORD_SCAN_CONCAT] PRIMARY KEY CLUSTERED 
(
	[id1] ASC,
	[id2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('WORD_SCAN_PROCESS1') IS NOT NULL
	DROP TABLE WORD_SCAN_PROCESS1
GO
CREATE TABLE [dbo].[WORD_SCAN_PROCESS1](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[originalid] [bigint] NOT NULL,
	[originalname] [varchar](500) NOT NULL,
	[seq] [int] NOT NULL,
	[name] [varchar](500) NOT NULL,
 CONSTRAINT [PK_WORD_SCAN_PROCESS1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF OBJECT_ID('WORD_SCAN_PROCESS2') IS NOT NULL
	DROP TABLE WORD_SCAN_PROCESS2
GO
CREATE TABLE [dbo].[WORD_SCAN_PROCESS2](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[originalid] [bigint] NOT NULL,
	[originalname] [varchar](500) NOT NULL,
	[seq] [int] NOT NULL,
	[name] [varchar](500) NOT NULL,
 CONSTRAINT [PK_WORD_SCAN_PROCESS2] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO